### ISSUE TITLE
Error during initialization of Autodesk.ADN.Toolkit.ViewAndData.Client

### ISSUE THREAD

**Issue by bampakoa** [Developer-Autodesk/ng-gallery#3]
Hi,

When I run the application with my credentials I get the following error:

    TypeError: Unable to get property 'ViewAndData' of undefined or null reference
    at $get (http://localhost:1914/node/ng-gallery/build/gallery.app.min.js:318:14)
    at e (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:36:306)
    at Anonymous function (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:38:101)
    at d (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:35:498)
    at e (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:36:248)
    at instantiate (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:36:430)
    at Anonymous function (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:76:45)
    at link (http://localhost:1914/node/ng-gallery/lib/bower_components/angular-route/angular-route.min.js:7:266)
    at $ (http://localhost:1914/node/ng-gallery/lib/bower_components/angular/angular.min.js:70:197)
    at B (http
    angular.min.js (102,318)

After some debugging I found that the problem appears during initialization of the client in **Autodesk.ADN.Toolkit.ViewData.Service.ViewAndData**

It seems that the Angular application cannot recognize the exported module from **view-and-data-client.js**

Thanks

**Comment by leefsmp** [comment]
Hi, I've just updated the sample and the readme instructions. Should work fine if you follow them. Let me know if any issue.

**Comment by bampakoa** [comment]
Thanks @leefsmp . The updated code fixed the problem.
